// solid-js/src/app/templates/todo-new.tsx
import { availableStatus, type AvailableStatus } from '../available-status';

import type { Accessor } from 'solid-js';

const MODIFIER_DISABLED = 'js:c-todo-new--disabled';
const MODIFIER_WAIT = 'js:c-todo-new--wait';

let appRef: Parameters<typeof inject>[0] | undefined;

function inject(api: {
	addTodo: (title: string) => void;
	status: Accessor<AvailableStatus>;
}) {
	if (appRef) return;
	appRef = api;
}

const newDisabled = (status: Accessor<AvailableStatus>) =>
	status() !== availableStatus.READY;

const newDisabledString = (status: Accessor<AvailableStatus>) =>
	newDisabled(status) ? 'true' : 'false';

const newDisabledClass = (status: Accessor<AvailableStatus>) =>
	newDisabled(status) ? MODIFIER_DISABLED : '';

const removeTodoClass = (status: Accessor<AvailableStatus>) => {
	let names = 'c-todo-new__submit';
	const value = status();
	if (value === availableStatus.READY) return names;

	names += ' ' + MODIFIER_DISABLED;
	return value === availableStatus.WAIT ? names + ' ' + MODIFIER_WAIT : names;
};

function TodoNew() {
	if (!appRef) throw new Error('API from App not injected yet');
	const app = appRef;

	let inputRef: HTMLInputElement | undefined;
	let submitRef: HTMLButtonElement | undefined;
	const handleEvent = (event: Event) => {
		if (event.type === 'click' && event.target === submitRef) {
			event.preventDefault();
			if (app.status() !== availableStatus.READY || !inputRef) return;

			const title = inputRef.value;
			if (title.length < 1) return;

			inputRef.value = '';
			app.addTodo(title);
			return;
		}
	};

	return (
		<form class="c-todo-new">
			<input
				ref={inputRef}
				name="todo-title"
				type="text"
				placeholder="Add a new to do"
				class={newDisabledClass(app.status)}
			/>
			<button
				ref={submitRef}
				onClick={handleEvent}
				class={removeTodoClass(app.status)}
				aria-disabled={newDisabledString(app.status)}
			>
				✅
			</button>
		</form>
	);
}

export { TodoNew, inject };

// preact/src/app/ui/components/todo-new.tsx
// file: src/app/ui/components/todo-new.tsx
import { useRef } from 'preact/hooks';
import { availableStatus, type AvailableStatus } from '../../available-status';

const CLASS_SUBMIT = 'c-todo-new__submit';
const MODIFIER_DISABLED = 'js:c-todo-new--disabled';
const MODIFIER_WAIT = 'js:c-todo-new--wait';

function TodoNew(props: {
	addNewTodo: (title: string) => unknown;
	status: AvailableStatus;
}) {
	const newTitle = useRef<HTMLInputElement>(null);

	const submitNewTodo = (event: Event) => {
		event.preventDefault();
		const button = event.target;
		if (!(button instanceof HTMLButtonElement && newTitle.current)) return;

		const title = newTitle.current.value;
		if (title.length < 1) return;

		newTitle.current.value = '';
		props.addNewTodo(title);
	};

	const [disabledForAria, disabledAsClass, submitClass]: [
		'true' | 'false',
		string,
		string,
	] =
		props.status === availableStatus.WAIT
			? [
					'true',
					MODIFIER_DISABLED,
					`${CLASS_SUBMIT} ${MODIFIER_DISABLED} ${MODIFIER_WAIT}`,
			  ]
			: props.status !== availableStatus.READY
			  ? ['true', MODIFIER_DISABLED, `${CLASS_SUBMIT} ${MODIFIER_DISABLED}`]
			  : ['false', '', CLASS_SUBMIT];
	return (
		<form>
			<input
				ref={newTitle}
				name="todo-title"
				type="text"
				placeholder="Add a new to do"
				class={disabledAsClass}
			/>
			<button
				onClick={submitNewTodo}
				class={submitClass}
				aria-disabled={disabledForAria}
			>
				✅
			</button>
		</form>
	);
}

export { TodoNew };
